#' Brief: Plot Dependency Map and Save as HTML
#'
#' @description Creates an interactive visualisation of the dependency map generated by
#' `build_dependency_map()`. The function converts the named list of dependencies into
#' an edge list, builds node metadata, and renders a hierarchical graph using **visNetwork**.
#' The root function is highlighted in red for easy identification.
#'
#' @details The resulting graph is saved as a self-contained HTML file at the specified
#' output path. Nodes represent user-defined functions, and edges represent direct calls.
#'
#' @author Antonio Fratamico
#' @date 12/12/2025
#'
#' @importFrom visNetwork visNetwork visEdges visOptions visLayout visHierarchicalLayout
#' @importFrom htmlwidgets saveWidget
#' @param dep_map Named list where each name is a function and its value is a character
#' vector of functions it directly calls.
#' @param output_path Character. Directory to save the HTML file.
#' @param output_name Character. Base name for the HTML file (without extension).
#' @param root_name Character. The root function to highlight in red.
#' @return Invisibly returns the path to the saved HTML file.
#' @export

plot_dependency_graph <- function(dep_map, output_path, output_name, root_name) {
  stopifnot(requireNamespace("visNetwork", quietly = TRUE),
            requireNamespace("htmlwidgets", quietly = TRUE))

  # Ensure output directory exists
  dir.create(output_path, showWarnings = FALSE, recursive = TRUE)

  # Build edges from dep_map
  edges <- do.call(rbind, lapply(names(dep_map), function(fn) {
    tos <- dep_map[[fn]]
    if (length(tos) == 0) return(NULL)
    data.frame(from = fn, to = tos, stringsAsFactors = FALSE)
  }))
  if (is.null(edges)) edges <- data.frame(from = character(0), to = character(0))
  edges <- unique(edges)

  # Build nodes
  node_ids <- unique(c(names(dep_map), unlist(dep_map), root_name))
  nodes <- data.frame(
    id    = node_ids,
    label = node_ids,
    color = ifelse(node_ids == root_name, "red", "skyblue"),
    stringsAsFactors = FALSE
  )

  # Create visNetwork graph
  vis <- visNetwork::visNetwork(nodes, edges,
                                main = paste("Function Map of", root_name),
                                width = "100%") %>%
    visNetwork::visEdges(arrows = "to") %>%
    visNetwork::visOptions(highlightNearest = TRUE,
                           nodesIdSelection = list(enabled = TRUE, main = "Select by Function")) %>%
    visNetwork::visLayout(randomSeed = 567) %>%
    visNetwork::visHierarchicalLayout(direction = "LR", levelSeparation = 200)

  # Save HTML
  out_file <- file.path(output_path, paste0(output_name, ".html"))
  htmlwidgets::saveWidget(vis, file = out_file, selfcontained = TRUE)

  message(sprintf("Function map saved: %s", out_file))
  invisible(out_file)
}

